### ISSUE TITLE
Incorrect links in contributor form

### ISSUE THREAD

**Issue by jugglinmike** [tc39/agreements#2]
The text of the contributor form (which is currently maintained within the Google Forms service) has two incorrect URLs.

The reference to "the [...] Rules" does not resolve to a resource:

> [2] http://www.ecma-international.org/memento/EcmaRules.htm

And the reference to the "the BSD License alternative of the ECMA Software Submitter Contribution Form" redirects to [a more generic "Ecma IPR policies" page](https://www.ecma-international.org/policies/by-ipr/):

> [5] https://www.ecma-international.org/memento/Policies/Exhibit_B.pdf

/cc @littledan (as the only contributor to this repository in the past few years)

**Comment by littledan** [comment]
Thanks for filing this @jugglinmike ; I believe I've fixed these errors. Thanks to @ljharb and @Lubrsi for more recent pings on this topic.
